apiVersion: v1
clusters:
- name: my_cluster
  cluster:
    certificate-authority: ca-prod-dal10-my_cluster.pem
    server: https://169.47.234.18:27790
contexts:
- name: my_cluster
  context:
    cluster: my_cluster
    user: admin
    namespace: default
current-context: my_cluster
kind: Config
users:
- name: admin
  user:
    client-certificate: admin.pem
    client-key: admin-key.pem
